# .github/workflows/ci.yml
name: CI                                           # Workflow name

on:
  push:
    branches: [ main ]                             # Trigger on pushes to main
  pull_request:
    branches: [ main ]                             # Trigger on PRs into main

jobs:
  ci:
    runs-on: ubuntu-latest                         # GitHub-hosted Ubuntu x64 (glibc)

    services:
      mongodb:                                     # Spin up MongoDB for API tests
        image: mongo:7
        ports:
          - 27017:27017                            # Expose MongoDB to the job at 127.0.0.1:27017
        options: >-                                # Health check so steps wait for Mongo to be ready
          --health-cmd="mongosh --host 127.0.0.1 --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4                  # Pull repo contents

      # ---------------- Node toolchain ----------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'                       # Match your laptop (Node 22)
          # NOTE: no npm cache here because there are no lockfiles

      - name: Show Node/npm versions
        run: node -v && npm -v

      # Optional: keep npm quiet & deterministic-ish without locks
      - name: Set npm config (quiet)
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false

      # ---------------- Server: install → build → test ----------------
      - name: Install server deps                   # No lockfile, so use npm install
        working-directory: server
        run: npm install --no-audit --no-fund --include=optional

      - name: Build server (if applicable)
        working-directory: server
        run: npm run build --if-present

      - name: Wait for Mongo                        # Simple readiness check
        run: |
          echo "Waiting for Mongo on 127.0.0.1:27017..."
          sudo apt-get update -y
          sudo apt-get install -y netcat-openbsd
          for i in {1..60}; do
            nc -z 127.0.0.1 27017 && echo "Mongo is up!" && exit 0
            sleep 2
          done
          echo "Mongo did not become ready in time"; exit 1

      - name: Run server tests
        working-directory: server
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://127.0.0.1:27017/labassets_test
        run: npm test

      # ---------------- Client: install + build ----------------
      - name: Build client (Vite)
        working-directory: client
        shell: bash
        env:
             VITE_API_URL: http://localhost:4000/api
        run: |
          npm install --no-audit --no-fund
          # sanity: show what was installed (optional)
          npm ls rollup || true
          ls -la node_modules/@rollup || true
          node -e "console.log('rollup:', require.resolve('rollup')); console.log('native:', require.resolve('@rollup/rollup-linux-x64-gnu'))"
          npm run build

