# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --host 127.0.0.1 --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Show Node/npm versions
        run: node -v && npm -v

      - name: Quiet npm
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false

      # ---------- Server ----------
      - name: Install server deps
        working-directory: server
        run: npm install --no-audit --no-fund

      - name: Build server (if applicable)
        working-directory: server
        run: npm run build --if-present

      - name: Wait for Mongo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y netcat-openbsd
          for i in {1..60}; do
            nc -z 127.0.0.1 27017 && exit 0
            sleep 2
          done
          exit 1

      - name: Run server tests
        working-directory: server
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://127.0.0.1:27017/labassets_test
        run: npm test

      # ---------- Client ----------
      - name: Install client deps (applies overrides → uses Rollup WASM)
        working-directory: client
        run: npm install --no-audit --no-fund

      - name: Build client (Vite)
        working-directory: client
        env:
          VITE_API_URL: http://localhost:4000/api
        run: npm run build
