# .github/workflows/release-images.yml
name: Build & Push Docker Images                # Workflow name

on:
  push:
    tags: ['v*.*.*']                            # Run only when pushing a tag like v1.2.3

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read                            # Read access to repo contents
      packages: write                           # Push images to GHCR

    steps:
      - uses: actions/checkout@v4               # Clone the repository

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}         # Auth user
          password: ${{ secrets.GITHUB_TOKEN }} # Token from GitHub Actions

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- Server image ----
      - name: Build & push server
        uses: docker/build-push-action@v6
        with:
          context: ./server                     # Dockerfile must be in ./server
          push: true                            # Push image to GHCR
          tags: |
            ghcr.io/${{ github.repository }}/server:latest
            ghcr.io/${{ github.repository }}/server:${{ github.ref_name }}
          # Tags with 'latest' and with the git tag (e.g., v1.2.3)

      # ---- Client image ----
      - name: Build & push client
        uses: docker/build-push-action@v6
        with:
          context: ./client                     # Dockerfile must be in ./client
          push: true
          build-args: |                         # Pass build-time env if your Dockerfile uses it
            VITE_API_URL=/api
          tags: |
            ghcr.io/${{ github.repository }}/client:latest
            ghcr.io/${{ github.repository }}/client:${{ github.ref_name }}
          # Tags with 'latest' and with the git tag
