name: Build & Push Docker Images

on:
  push:
    tags: ['v*.*.*']

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ghcr.io/${{ github.repository }}/server:latest,ghcr.io/${{ github.repository }}/server:${{ github.ref_name }}

      - name: Build & push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          build-args: |
            VITE_API_URL=/api
          tags: ghcr.io/${{ github.repository }}/client:latest,ghcr.io/${{ github.repository }}/client:${{ github.ref_name }}
